name: cm_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.12.7
  http: ^0.12.0+2
  uuid: ^2.0.1
  firebase_auth: ^0.14.0+1
  google_sign_in: ^4.0.6
  flutter_signin_button: ^0.2.8
  firebase_messaging: ^5.1.3
  sliding_up_panel: ^0.3.4
  flutter_datetime_picker: ^1.2.6
  intl: ^0.15.8
  shared_preferences: ^0.5.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
